services:
  # Backend Service
  - type: web
    name: my-mern-backend
    env: node
    rootDirectory: backend  # Set root directory for backend
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health  # Ensure this route is defined in your backend
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://ecojedo:vjj3b0vIXxiAM6N5@cluster0.pmgff.mongodb.net
      - key: SECRET_KEY
        value: uKz2zkwWkw41p4tx
    plan: free

  # Frontend Service
  - type: static
    name: my-mern-frontend
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    publishPath: build  # This points to the folder where your frontend is built
